### ISSUE TITLE
Requests hang when doing `readBody()` when this middleware is enabled.

### ISSUE THREAD

**Issue by genu** [wobsoriano/h3-clerk#14]
I'm working through an issue where all POST requests hang, on `h3`'s method `readBody(..)`. 

From my findings, when I disable the `h3-clerk` middleware, it no longer hangs.

I'm not exactly sure what is going on, maybe some version mismatch between the h3 provided by this middleware and the one provided by nuxt? (since nuxt recently rolled out a new version)

I can put together a repro if necessary.

**Comment by wobsoriano** [comment]
Fixed in https://github.com/wobsoriano/h3-clerk/pull/15
