### ISSUE TITLE
One thing to upgrade!😊

### ISSUE THREAD

**Issue by ohiduzzamansiam1** [wobsoriano/h3-clerk#6]
Hey Brother!

The clerk support in nuxt is working perfectly in my application. But one thing I noticed that it's a little bit complicated when someone is beginner in this, he/she will not understand it well.

So, if you can make a library specially for Nuxt 3, like "vue-clerk", it will be so much easy to get on.

I hope you'll work on it and build something much much better. Take love brother from Bangladesh.💝

**Comment by wobsoriano** [comment]
`vue-clerk` exists! - https://github.com/wobsoriano/vue-clerk

A combo of `h3-clerk` and `vue-clerk` - https://github.com/wobsoriano/nuxt-clerk-template
